@extends('pages.theme.main')
@section('title', 'Disclaimer')
@section('styles')
<style>
    .custom-margin-top{
        margin-top: 20px!important;
    }
    @media only screen and (max-width: 425px) {
        .custom-margin-top{
            margin-top: 55px!important;
        }
    }
</style>
@endsection
@section('content')
<div class="rainbow-cta-area rainbow-section-gap rainbow-section-gapBottom-big">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="content-page pb--50 mt-3">
                    <div class="chat-box-list">
                        <div class="content">
                            <div class="rainbow-accordion-style accordion rainbow-section-gapBottom">
                                <div class="banner-area custom-margin-top">
                                    <div class="settings-area">
                                        <h3 class="title">Disclaimer</h3>
                                    </div>
                                </div>
                                <div class="content-page pb--50">
                            <div class="chat-box-list">
                                <div class="content">
                                    <h4>1) For Educational and Guidance Purposes Only</h4>
                                    <ul>
                                        <li>The scores, feedback, gap analysis, model answers, and all other content within the Evaluation Reports generated by Aspire Scan are provided for educational, practice, and guidance purposes only.</li>
                                    </ul>
                                    <h4>2) Not a Guarantee of Success</h4>
                                    <ul>
                                        <li>The use of our Service is a diagnostic tool designed to help you identify your strengths and weaknesses in answer writing. Potenzials Education does not, in any way, guarantee success, selection, or any specific score in the actual UPSC Civil Services Examination or any other examination. The AI evaluation is a means for practice and should not be considered a definitive prediction of your actual performance.</li>
                                    </ul>
                                    <h4>3) Inherent Limitations of Artificial Intelligence</h4>
                                    <ul>
                                        <li>While our AI is highly advanced, it is an automated system and has inherent limitations. It may be subject to occasional errors, inaccuracies, or misinterpretations of handwriting or content. The feedback provided is generated by an algorithm and should be used in conjunction with your own judgment and other study materials.</li>
                                    </ul>
                                    <h4>4) Not a Substitute for Human Mentorship</h4>
                                    <ul>
                                        <li>Aspire Scan is designed to complement your studies, not to replace professional human guidance. The insights provided by our AI should be considered an additional resource alongside the mentorship of experienced teachers and mentors.</li>
                                        <li>By using the Aspire Scan service, you acknowledge that you have read, understood, and agree to the terms of this disclaimer. You agree to use the service at your own risk.</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection